# gh-codespace-cp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-codespace-cp.1.gz
complete -c gh-codespace-cp -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-cp -s e -l expand -d 'Expand remote file names on remote shell'
complete -c gh-codespace-cp -s p -l profile -d 'Name of the SSH profile to use'
complete -c gh-codespace-cp -s r -l recursive -d 'Recursively copy directories EXAMPLE $ gh codespace cp -e README'

