# gh-codespace-create
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-codespace-create.1.gz
complete -c gh-codespace-create -s b -l branch -d 'repository branch'
complete -c gh-codespace-create -l default-permissions -d 'do not prompt to accept additional permissions requested by the codespace'
complete -c gh-codespace-create -l idle-timeout -d 'allowed inactivity before codespace is stopped, e. g.  "10m", "1h"'
complete -c gh-codespace-create -s m -l machine -d 'hardware specifications for the VM'
complete -c gh-codespace-create -s r -l repo -d 'repository name with owner: user/repo'
complete -c gh-codespace-create -s s -l status -d 'show status of post-create command and dotfiles SEE ALSO'

