# gh-codespace-edit
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-codespace-edit.1.gz
complete -c gh-codespace-edit -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-edit -s d -l displayName -d 'display name'
complete -c gh-codespace-edit -l idle-timeout -d 'allowed inactivity before codespace is stopped, e. g.  "10m", "1h"'
complete -c gh-codespace-edit -s m -l machine -d 'hardware specifications for the VM SEE ALSO'

