# gh-completion
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-completion.1.gz
complete -c gh-completion -s s -l shell -d 'Shell type: {bash|zsh|fish|powershell} SEE ALSO'

