# gh-codespace-ports-forward
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-codespace-ports-forward.1.gz
complete -c gh-codespace-ports-forward -s c -l codespace -d 'Name of the codespace SEE ALSO'

